dependencies:
  - Openzeppelin/openzeppelin-contracts@4.2.0
  - smartcontractkit/chainlink-brownie-contracts@0.2.2
compiler:
  solc:
    remappings:
      - '@openzeppelin=Openzeppelin/openzeppelin-contracts@4.2.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.2'